name 'webdeploymenttoolkit'
maintainer 'Patrick McMorran'
maintainer_email 'kingrolloinc@sbcglobal.net'
license 'The Unlicense'
description 'Installs/Configures webdeploymenttoolkit'
long_description 'Installs/Configures webdeploymenttoolkit'
version '0.1.0'
