name 'webdeploymenttoolkit'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures webdeploymenttoolkit'
long_description 'Installs/Configures webdeploymenttoolkit'
version '0.1.0'
